# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cal_V2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import image_rc2


class UiMainWindow(object):

    def __init__(self):
        self.BUTTON_COL = 4
        self.BUTTON_ROW = 5
        self.maintext_fontsize = 48
        self.STACKTEXT_FONTSIZE = 14
        self.entry_text = '0'
        self.stack_text = ''
        self.last_entry = ''

        self.equal_state = False
        self.last_operator = ''

       
        self.button_arr = []
        self.button_value = [['CE', 'C', 'DEL', '÷'], 
                             ['7', '8', '9', 'x'],
                             ['4', '5', '6', '-'],
                             ['1', '2', '3', '+'],
                             ['+/-','0','.','=']]
        
      
    def button_setting(self):
        button_index = 0
        for row in range (self.BUTTON_ROW) :
            for col in range (self.BUTTON_COL):
                button_index += 1
                self.button_arr.append(getattr(self,"push_button_%d" %button_index))
       
        

            
        

    def button_add_event(self): 
        
        for index,button in enumerate(self.button_arr):

            row = index // self.BUTTON_COL
            col = index % self.BUTTON_COL
            
            button.clicked.connect(lambda f, text = self.button_value[row][col] :self.set_labeltext(text) )
        
        
            
    
    def update_textlabel(self,obj,text,fontsize):
        obj.setText(self._translate(
            "MainWindow", "<html><head/><body><p><span style=\" font-size:+"+str(fontsize)+"pt; color:#ffffff;\">"+text+"</span></p></body></html>"))
    
    def update_entry_textlabel(self):
        if self.entry_text == "Cannot divide by zero":
            self.maintext_fontsize = 29
        else:
            self.maintext_fontsize = 48
        
        self.update_textlabel(self.main_textlabel,self.entry_text,self.maintext_fontsize)
    
    def update_stack_textlabel(self):
       
        self.update_textlabel(self.stack_textlabel,self.stack_text,self.STACKTEXT_FONTSIZE)

    def calculate(self):
        text_cal = ''
        for c in self.stack_text:
            if c == 'x':
                text_cal += '*'
            elif c == '÷':
                text_cal += '/'
            else:
                text_cal += c
        try:
            output = str(eval(text_cal))
            return output
            
        except ZeroDivisionError:
            return "Cannot divide by zero"
            

        


    def set_labeltext(self,text):


        
     

        if text == 'DEL':

            self.entry_text = self.entry_text[:-1]

            if len(self.entry_text) == 0:
                self.entry_text = '0' 
        

        elif text == '+/-':
            if len(self.entry_text) == 0:
                self.entry_text = '-' + self.last_entry
            elif self.entry_text[0] != '0' :
                if self.entry_text[0].isnumeric():
                    self.entry_text = '-' + self.entry_text
                elif self.entry_text[0] == '-':
                    self.entry_text = self.entry_text[1:] 


        

        elif text == '=':
            
            
            if len(self.stack_text) == 0:
                self.stack_text = self.entry_text +self.last_operator + self.last_entry  ## when you want to calculate with last entry (press '=' repidly)

            elif self.stack_text[-1] in '+-x÷':
                self.stack_text += self.last_entry

            else:
                self.last_entry = self.entry_text
                self.stack_text += self.entry_text

            
            self.entry_text =  self.calculate()   # calculate from evaluate

            
            self.stack_text += text

            equal_state = True
                
            self.update_stack_textlabel()
            self.update_entry_textlabel()
            if self.entry_text == "Cannot divide by zero" :
                self.entry_text = '0'
                self.stack_text = ''
                self.update_stack_textlabel()
            self.stack_text = ''
          
            
            # print("Entry:"+self.entry_text+"\tStack:"+self.stack_text)

            return

         

        elif text == "CE" :
            self.entry_text = '0'
           

        elif text == "C":
            self.entry_text = '0'
            self.stack_text = ''
            self.last_entry = ''
            self.last_operator = ''
            

        elif text in '+-x÷':
            self.last_operator = text   

            if len(self.entry_text) == 0 :
                self.stack_text = self.entry_text + self.stack_text[:-1]   ## inherit operator
            else:   
                self.stack_text += self.entry_text
       
            self.entry_text = self.calculate()
           
            self.stack_text += text
            self.update_entry_textlabel()
            self.update_stack_textlabel()

            if self.entry_text == "Cannot divide by zero" :
                self.entry_text = '0'
                self.stack_text = ''
                self.update_stack_textlabel()
            else:
                self.last_entry = self.entry_text
   
            self.entry_text = ''
           

            # print("Entry:"+self.entry_text+"\tStack:"+self.stack_text)
            return
           
        
        else:
            
            if text =='.' and (self.entry_text[-1] == '.' or '.' in self.entry_text) :
                pass
           
            elif ((len(self.entry_text) ==0 or self.entry_text[0] == '0') and '.' not in self.entry_text) :
               
                self.entry_text = text
                if text == '.':
                    self.entry_text = "0."
                
            else:
                self.entry_text += text
            self.last_entry = self.entry_text

       
           
        # print("Entry:"+self.entry_text+"\tStack:"+self.stack_text)
        self.update_entry_textlabel()
        self.update_stack_textlabel()

    def retranslateUi(self, MainWindow):
        self._translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(self._translate("MainWindow", "Calculator"))
        
        self.update_stack_textlabel()
        self.update_entry_textlabel()


        for index,button in enumerate(self.button_arr):

            row = index // self.BUTTON_COL
            col = index % self.BUTTON_COL
          
            button.setText(self._translate("MainWindow",self.button_value[row][col]))

 
        

    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 550)
        # print(MainWindow.getsz)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(450, 550))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(
            "background-image: url(:/cal_img/orange_color.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screem_grid = QtWidgets.QGridLayout(self.centralwidget)
        self.screem_grid.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.screem_grid.setContentsMargins(-1, 20, -1, 0)
        self.screem_grid.setHorizontalSpacing(0)
        self.screem_grid.setVerticalSpacing(15)
        self.screem_grid.setObjectName("screem_grid")
        self.main_textlabel = QtWidgets.QLabel(self.centralwidget)
        self.main_textlabel.setMinimumSize(QtCore.QSize(0, 150))
        self.main_textlabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_textlabel.setStyleSheet(
            "background-image: url(:/cal_img/orange_color.png);")
        self.main_textlabel.setTextFormat(QtCore.Qt.AutoText)
        self.main_textlabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.main_textlabel.setObjectName("main_textlabel")
        self.screem_grid.addWidget(self.main_textlabel, 1, 0, 1, 1)
        self.numpad_grid = QtWidgets.QGridLayout()
        self.numpad_grid.setHorizontalSpacing(10)
        self.numpad_grid.setVerticalSpacing(5)
        self.numpad_grid.setObjectName("numpad_grid")
        self.push_button_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_9.sizePolicy().hasHeightForWidth())
        self.push_button_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_9.setFont(font)
        self.push_button_9.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_9.setObjectName("push_button_9")
        self.numpad_grid.addWidget(self.push_button_9, 10, 0, 1, 1)
        self.push_button_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_7.sizePolicy().hasHeightForWidth())
        self.push_button_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_7.setFont(font)
        self.push_button_7.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_7.setObjectName("push_button_7")
        self.numpad_grid.addWidget(self.push_button_7, 5, 2, 1, 1)
        self.push_button_13 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_13.sizePolicy().hasHeightForWidth())
        self.push_button_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_13.setFont(font)
        self.push_button_13.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_13.setObjectName("push_button_13")
        self.numpad_grid.addWidget(self.push_button_13, 11, 0, 1, 1)
        self.push_button_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_5.sizePolicy().hasHeightForWidth())
        self.push_button_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_5.setFont(font)
        self.push_button_5.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_5.setObjectName("push_button_5")
        self.numpad_grid.addWidget(self.push_button_5, 5, 0, 1, 1)
        self.push_button_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_17.sizePolicy().hasHeightForWidth())
        self.push_button_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_17.setFont(font)
        self.push_button_17.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_17.setObjectName("push_button_17")
        self.numpad_grid.addWidget(self.push_button_17, 14, 0, 1, 1)
        self.push_button_12 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_12.sizePolicy().hasHeightForWidth())
        self.push_button_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_12.setFont(font)
        self.push_button_12.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_12.setObjectName("push_button_12")
        self.numpad_grid.addWidget(self.push_button_12, 10, 4, 1, 1)
        self.push_button_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_4.sizePolicy().hasHeightForWidth())
        self.push_button_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_4.setFont(font)
        self.push_button_4.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_4.setObjectName("push_button_4")
        self.numpad_grid.addWidget(self.push_button_4, 3, 4, 1, 1)
        self.push_button_20 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_20.sizePolicy().hasHeightForWidth())
        self.push_button_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_20.setFont(font)
        self.push_button_20.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_20.setObjectName("push_button_20")
        self.numpad_grid.addWidget(self.push_button_20, 14, 4, 1, 1)
        self.push_button_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_8.sizePolicy().hasHeightForWidth())
        self.push_button_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_8.setFont(font)
        self.push_button_8.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_8.setObjectName("push_button_8")
        self.numpad_grid.addWidget(self.push_button_8, 5, 4, 1, 1)
        self.push_button_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_6.sizePolicy().hasHeightForWidth())
        self.push_button_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_6.setFont(font)
        self.push_button_6.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_6.setObjectName("push_button_6")
        self.numpad_grid.addWidget(self.push_button_6, 5, 1, 1, 1)
        self.push_button_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_1.sizePolicy().hasHeightForWidth())
        self.push_button_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_1.setFont(font)
        self.push_button_1.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_1.setObjectName("push_button_1")
        self.numpad_grid.addWidget(self.push_button_1, 3, 0, 1, 1)
        self.push_button_14 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_14.sizePolicy().hasHeightForWidth())
        self.push_button_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_14.setFont(font)
        self.push_button_14.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_14.setObjectName("push_button_14")
        self.numpad_grid.addWidget(self.push_button_14, 11, 1, 1, 1)
        self.push_button_15 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_15.sizePolicy().hasHeightForWidth())
        self.push_button_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_15.setFont(font)
        self.push_button_15.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_15.setObjectName("push_button_15")
        self.numpad_grid.addWidget(self.push_button_15, 11, 2, 1, 1)
        self.push_button_11 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_11.sizePolicy().hasHeightForWidth())
        self.push_button_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_11.setFont(font)
        self.push_button_11.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_11.setObjectName("push_button_11")
        self.numpad_grid.addWidget(self.push_button_11, 10, 2, 1, 1)
        self.push_button_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_3.sizePolicy().hasHeightForWidth())
        self.push_button_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_3.setFont(font)
        self.push_button_3.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_3.setObjectName("push_button_3")
        self.numpad_grid.addWidget(self.push_button_3, 3, 2, 1, 1)
        self.push_button_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_2.sizePolicy().hasHeightForWidth())
        self.push_button_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_2.setFont(font)
        self.push_button_2.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                         "color: rgb(255, 255, 255);")
        self.push_button_2.setObjectName("push_button_2")
        self.numpad_grid.addWidget(self.push_button_2, 3, 1, 1, 1)
        self.push_button_16 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_16.sizePolicy().hasHeightForWidth())
        self.push_button_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_16.setFont(font)
        self.push_button_16.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_16.setObjectName("push_button_16")
        self.numpad_grid.addWidget(self.push_button_16, 11, 4, 1, 1)
        self.push_button_10 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_10.sizePolicy().hasHeightForWidth())
        self.push_button_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_10.setFont(font)
        self.push_button_10.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_10.setObjectName("push_button_10")
        self.numpad_grid.addWidget(self.push_button_10, 10, 1, 1, 1)
        self.push_button_19 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_19.sizePolicy().hasHeightForWidth())
        self.push_button_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_19.setFont(font)
        self.push_button_19.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_19.setObjectName("push_button_19")
        self.numpad_grid.addWidget(self.push_button_19, 14, 2, 1, 1)
        self.push_button_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.push_button_18.sizePolicy().hasHeightForWidth())
        self.push_button_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.push_button_18.setFont(font)
        self.push_button_18.setStyleSheet("background-image: url(:/cal_img/orange_color.png);\n"
                                          "color: rgb(255, 255, 255);")
        self.push_button_18.setObjectName("push_button_18")
        self.numpad_grid.addWidget(self.push_button_18, 14, 1, 1, 1)
        self.screem_grid.addLayout(self.numpad_grid, 2, 0, 1, 1)
        self.stack_textlabel = QtWidgets.QLabel(self.centralwidget)
        self.stack_textlabel.setMinimumSize(QtCore.QSize(0, 20))
        self.stack_textlabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stack_textlabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.stack_textlabel.setObjectName("stack_textlabel")
        self.screem_grid.addWidget(self.stack_textlabel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

      
        self.button_setting()
        self.button_add_event()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
  
    ui = UiMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
